<?php
namespace app\admin\logical;
use app\common\controller\Backend;
use think\Request;

class Rbacl extends Backend
{
    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 输出获取的所有用户的信息
     * @param array $users   用户信息 ，里面包含两个属性，用户信息列表-data 和查找的所有符合条件的数据量-count
     */
    public function showUser($users=[]){
        if(empty($users['count']) or empty($users['data']))
            outputJson(-2,'失败');
        outputJson(1,'成功',$users['count'],$users['data']);
    }

    /**
     * 添加用户
     * @param $userInfo，用户信息
     */
    public function addUser($userInfo){

    }
}