<?php
namespace app\admin\model\rbac;
use app\common\model\BasicModel;
use \think\model;
class Organize extends BasicModel
{
    protected $field = true;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * @param array $condition
     * @param int $limit
     * @param int $page
     * @param string $fileds
     * @return mixed
     */
    public function listOrganize($condition=[],$limit=10,$page=1,$fileds='*'){
        return $this->getInfo($this,$fileds,$condition,$limit,$page);
    }

       /*
     * 获取全部组名称
     */
    public function listallOrganize($condition = [])
    {
        return parent::getAllInfo($this,$condition); // TODO: Change the autogenerated stub
    }


    /**
     * 组织数据保存
     * @param array $data  组织信息
     *                  里面的type属性  add----新增，  edit----编辑
     * @return bool
     */
    public function saveOrganize($data){
        if(empty($data['type']))
            return false;
        $type=$data['type'];
        unset($data['type']);
        //编辑
        if($type=='edit')
            return $this->saveInfo($this,$data,['o_id'=>$data['o_id']]);
        //新增
        return $this->saveInfo($this,$data);
    }

    public function getallOrganize($condition){
        return $this->getAllInfo($this,$condition);
    }
}