<?php
namespace app\admin\model\rbac;
use app\common\model\BasicModel;
class UserGroup extends BasicModel
{
    protected $table=[

    ];
    protected $field = true;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $condition
     * @param int $limit
     * @param int $page
     * @param string $fileds
     * @return mixed
     */
    public function saveUserGroup($data){
        if(empty($data['type']))
            return false;
        $type=$data['type'];
        unset($data['type']);
        //编辑
        if($type=='edit')
            return $this->saveInfo($this,$data,['ug_id'=>$data['ug_id']]);
        //新增
        return $this->saveInfo($this,$data);
    }
}