<?php
namespace app\admin\model\rbac;
use app\common\model\BasicModel;
class User extends BasicModel
{
    protected $table=[

    ];
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function listUser($condition=[],$limit=10,$page=1,$fileds='*'){
        return $this->getUserinfo('User',$fileds,$condition,$limit,$page);
    }
}