<?php
namespace app\admin\model\rbac;
use app\common\model\BasicModel;
class UserRole extends BasicModel
{
    protected $table=[

    ];
    protected $field = true;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $condition
     * @param int $limit
     * @param int $page
     * @param string $fileds
     * @return mixed
     */
    public function saveUserRole($data){
        if(empty($data['type']))
            return false;
        $type=$data['type'];
        unset($data['type']);
        //编辑
        if($type=='edit')
            return $this->saveInfo($this,$data,['ur_id'=>$data['ur_id']]);
        //新增
        return $this->saveInfo($this,$data);
    }

    /**
     * 删除用户-角色映射关系
     * @param $data
     */
    public function deleteUserRole($data){
        if(empty($data['u_id']))
            return false;
        return $this->deleteInfo(['u_id'=>$data['u_id']]);
    }
}