<?php
namespace app\admin\model\rbac;
use app\common\model\BasicModel;
class User extends BasicModel
{
    protected $table=[

    ];
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function listUser(){
        $fileds='*';
        $condition['where']['u_id']=6;
        return $this->getUserinfo('User',$fileds,$condition);
    }
}